---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install Dependencies
  become: yes
  ansible.builtin.apt:
    name: "{{ pb_dep }}"
    update_cache: yes

- name: Download PKGBUILD
  delegate_to: localhost
  ansible.builtin.get_url:
    url: "{{ pb_pkgbuild.url }}"
    dest: "{{ pb_pkgbuild.dest }}"
  when: "'protonmail-bridge' not in ansible_facts.packages"

- name: Download protonmail-bridge package
  ansible.builtin.get_url:
    url: "{{ lookup('file', pb_pkgbuild.dest) | regex_search('(http.*\\.deb)') }}"
    dest: "{{ remote_tmp_dir }}/protonmail-bridge.deb"
  when: "'protonmail-bridge' not in ansible_facts.packages"

- name: Install protonmail-bridge package
  become: yes
  ansible.builtin.apt:
    deb: "{{ remote_tmp_dir }}/protonmail-bridge.deb"
  when: "'protonmail-bridge' not in ansible_facts.packages"
