---
- name: Check GPG key
  become: yes
  become_user: "{{ proton_local_user }}"
  ansible.builtin.shell:
    cmd: "{{ cmd_gpg_list }}"
  register: gpg_list
  changed_when: '"ProtonMail Bridge" not in gpg_list.stdout'

- name: Copy GPG key
  become: yes
  become_user: "{{ proton_local_user }}"
  ansible.builtin.template:
    src: templates/gpg_config.j2
    dest: "{{ proton_local_user_home }}/gpg_config"
    owner: "{{ proton_local_user }}"
    group: "{{ proton_local_user }}"
  when: '"ProtonMail Bridge" not in gpg_list.stdout'

- name: Create GPG key
  become: yes
  become_user: "{{ proton_local_user }}"
  ansible.builtin.shell:
    cmd: "{{ cmd_gpg_gen }} {{proton_local_user_home}}/gpg_config"
  when: '"ProtonMail Bridge" not in gpg_list.stdout'
